spring.application.name=spring_kadai_todo

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPAのテーブル生成後にdata.sqlを実行する
spring.jpa.defer-datasource-initialization=true

# 常にdata.sqlを実行する
spring.sql.init.mode=always

# （任意）テーブルが存在しない場合にエラーにならないようにする
# spring.jpa.hibernate.ddl-auto=update